---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 4
  selector:
    matchLabels:
      name: app2
  template:
    metadata:
      labels:
        name: app2
    spec:
      containers:
        - name: app2
          image: job2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082

