---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 4
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
        - name: app1
          image: job1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

