---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  ports:
    - name: tcp
      port: 8080
      targetPort: 8081
  selector:
    name: api-route

